"""Search Provider SDK for Kancell Shield v3.

This module provides the SDK for implementing search providers
that integrate with the Search Engine.
"""

from .models import (
    AuthMethod,
    ErrorSeverity,
    HealthStatus,
    LimitScope,
    PaginationState,
    PaginationType,
    ProviderAuthentication,
    ProviderCapabilities,
    ProviderConfiguration,
    ProviderFeatureFlags,
    ProviderHealthStatus,
    ProviderInfo,
    ProviderRequest,
    ProviderResponse,
    ProviderStatistics,
    ProviderVersion,
    RateLimitInfo,
    RateLimitType,
)

from .interfaces import (
    Provider,
    ProviderAction,
    ProviderAuthenticator,
    ProviderCapabilityResolver,
    ProviderErrorHandler,
    ProviderFactory,
    ProviderHealthChecker,
    ProviderPaginator,
    ProviderRateLimiter,
    ProviderRegistry,
)

from .context import ProviderContext
from .factory import MockProvider, ProviderFactoryImpl, ProviderRegistryImpl
from .health import AggregatedHealthChecker, HealthMetrics, ProviderHealthCheckerImpl
from .capabilities import (
    CapabilityMatch,
    CapabilityResolverImpl,
    LenientCapabilityResolver,
    StrictCapabilityResolver,
)
from .authentication import AuthState, MockAuthenticator, ProviderAuthenticatorImpl
from .pagination import (
    BatchPaginator,
    CursorPaginator,
    OffsetPaginator,
    PagePaginator,
    ProviderPaginatorImpl,
)
from .rate_limiter import (
    FixedWindow,
    GlobalRateLimiter,
    ProviderRateLimiterImpl,
    SlidingWindow,
    TokenBucket,
)
from .exceptions import (
    AuthenticationError,
    BackoffRequiredError,
    CapabilityError,
    ConfigurationError,
    ExpiredTokenError,
    HealthCheckError,
    InvalidCredentialsError,
    NetworkError,
    OAuthError,
    PaginationError,
    ParseError,
    ProviderAlreadyRegisteredError,
    ProviderError,
    ProviderNotFoundError,
    QuotaError,
    QuotaExceededError,
    RateLimitError,
    RequestError,
    ResponseError,
    ServerError,
    TimeoutError,
    ValidationError,
    VersionError,
)

__all__ = [
    # Enums
    "AuthMethod",
    "ErrorSeverity",
    "HealthStatus",
    "LimitScope",
    "PaginationType",
    "RateLimitType",
    # Models
    "PaginationState",
    "ProviderAuthentication",
    "ProviderCapabilities",
    "ProviderConfiguration",
    "ProviderFeatureFlags",
    "ProviderHealthStatus",
    "ProviderInfo",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderStatistics",
    "ProviderVersion",
    "RateLimitInfo",
    # Interfaces
    "Provider",
    "ProviderAction",
    "ProviderAuthenticator",
    "ProviderCapabilityResolver",
    "ProviderErrorHandler",
    "ProviderFactory",
    "ProviderHealthChecker",
    "ProviderPaginator",
    "ProviderRateLimiter",
    "ProviderRegistry",
    # Implementations
    "ProviderContext",
    "ProviderFactoryImpl",
    "ProviderRegistryImpl",
    "ProviderHealthCheckerImpl",
    "CapabilityResolverImpl",
    "ProviderAuthenticatorImpl",
    "ProviderPaginatorImpl",
    "ProviderRateLimiterImpl",
    # Additional classes
    "MockProvider",
    "MockAuthenticator",
    "TokenBucket",
    "SlidingWindow",
    "FixedWindow",
    "GlobalRateLimiter",
    "AggregatedHealthChecker",
    "StrictCapabilityResolver",
    "LenientCapabilityResolver",
    "BatchPaginator",
    "OffsetPaginator",
    "CursorPaginator",
    "PagePaginator",
    "AuthState",
    "HealthMetrics",
    "CapabilityMatch",
    # Exceptions
    "ProviderError",
    "ConfigurationError",
    "AuthenticationError",
    "InvalidCredentialsError",
    "ExpiredTokenError",
    "OAuthError",
    "RateLimitError",
    "QuotaExceededError",
    "BackoffRequiredError",
    "RequestError",
    "ValidationError",
    "TimeoutError",
    "NetworkError",
    "ResponseError",
    "ParseError",
    "QuotaError",
    "ServerError",
    "ProviderNotFoundError",
    "ProviderAlreadyRegisteredError",
    "CapabilityError",
    "HealthCheckError",
    "PaginationError",
    "VersionError",
]
