"""Core domain model for Kancell Shield v3.

This module contains shared domain types, value objects,
identifiers, enums, and exceptions.
"""

from .constants import (
    DEFAULT_BATCH_SIZE,
    DEFAULT_PRIORITY,
    DEFAULT_QUEUE_CAPACITY,
    DEFAULT_RATE_LIMIT,
    DEFAULT_RETRY_COUNT,
    DEFAULT_SCORE,
    DEFAULT_TIMEOUT,
    HIGH_CONFIDENCE,
    HIGH_PRIORITY,
    HIGH_RISK_TLDS,
    HIGH_SCORE_THRESHOLD,
    LOW_CONFIDENCE,
    LOW_PRIORITY,
    LOW_RISK_TLDS,
    MAX_BATCH_SIZE,
    MAX_CANDIDATE_ID_LENGTH,
    MAX_DOMAIN_LENGTH,
    MAX_EVENT_ID_LENGTH,
    MAX_HOST_LENGTH,
    MAX_PORT,
    MAX_PRIORITY,
    MAX_PROVIDER_ID_LENGTH,
    MAX_QUEUE_CAPACITY,
    MAX_RATE_LIMIT,
    MAX_RETRY_COUNT,
    MAX_RULE_ID_LENGTH,
    MAX_SCORE,
    MAX_SOURCE_ID_LENGTH,
    MAX_TASK_ID_LENGTH,
    MAX_TIMEOUT,
    MAX_URL_LENGTH,
    MEDIUM_CONFIDENCE,
    MIN_BATCH_SIZE,
    MIN_DOMAIN_LENGTH,
    MIN_DOMAIN_LABELS,
    MIN_LABEL_LENGTH,
    MIN_PRIORITY,
    MIN_RETRY_COUNT,
    MIN_SCORE,
    MIN_TIMEOUT,
    RESERVED_TLDS,
)

from .enums import (
    CandidateStatus,
    DiscoveryStatus,
    PriorityLevel,
    ProviderStatus,
    ScoreLevel,
)

from .exceptions import (
    ConfigurationError,
    DomainValidationError,
    IdentifierError,
    KancellShieldError,
    PriorityValidationError,
    ResourceError,
    ScoreValidationError,
    StateError,
    URLValidationError,
    ValidationError,
)

from .identifiers import (
    BatchId,
    CandidateId,
    EventId,
    ProviderId,
    RuleId,
    SourceId,
    TaskId,
)

from .types import (
    ConfidenceScore as ConfidenceScoreType,
    DiscoveryTask,
    DomainName,
    EventData,
    EventEmitter,
    EventHandler,
    FilterFunc,
    is_active_status,
    is_terminal_status,
    is_valid_domain,
    is_valid_priority,
    is_valid_score,
    is_valid_url,
    JSON,
    Metadata,
    ProviderName,
    SearchProvider,
    ScoreFunc,
    ValidationFunc,
)

from .value_objects import (
    ConfidenceScore,
    Domain,
    Hostname,
    Priority,
    Timestamp,
    URL,
)


__all__ = [
    # Constants - Domain
    "MAX_DOMAIN_LENGTH",
    "MIN_DOMAIN_LENGTH",
    "MIN_DOMAIN_LABELS",
    "MIN_LABEL_LENGTH",
    "MAX_LABEL_LENGTH",
    # Constants - URL
    "MAX_URL_LENGTH",
    "MAX_HOST_LENGTH",
    "MAX_PORT",
    # Constants - Score
    "MIN_SCORE",
    "MAX_SCORE",
    "DEFAULT_SCORE",
    "HIGH_SCORE_THRESHOLD",
    "LOW_SCORE_THRESHOLD",
    "HIGH_CONFIDENCE",
    "MEDIUM_CONFIDENCE",
    "LOW_CONFIDENCE",
    # Constants - Priority
    "MIN_PRIORITY",
    "MAX_PRIORITY",
    "DEFAULT_PRIORITY",
    "HIGH_PRIORITY",
    "LOW_PRIORITY",
    # Constants - Queue
    "DEFAULT_QUEUE_CAPACITY",
    "MAX_QUEUE_CAPACITY",
    # Constants - Batch
    "DEFAULT_BATCH_SIZE",
    "MAX_BATCH_SIZE",
    "MIN_BATCH_SIZE",
    # Constants - Timeout
    "DEFAULT_TIMEOUT",
    "MAX_TIMEOUT",
    "MIN_TIMEOUT",
    # Constants - Retry
    "DEFAULT_RETRY_COUNT",
    "MAX_RETRY_COUNT",
    "MIN_RETRY_COUNT",
    # Constants - Rate
    "DEFAULT_RATE_LIMIT",
    "MAX_RATE_LIMIT",
    "MIN_RATE_LIMIT",
    # Constants - Identifiers
    "MAX_PROVIDER_ID_LENGTH",
    "MAX_CANDIDATE_ID_LENGTH",
    "MAX_TASK_ID_LENGTH",
    "MAX_BATCH_ID_LENGTH",
    "MAX_EVENT_ID_LENGTH",
    "MAX_SOURCE_ID_LENGTH",
    "MAX_RULE_ID_LENGTH",
    # Constants - TLD
    "RESERVED_TLDS",
    "HIGH_RISK_TLDS",
    "LOW_RISK_TLDS",
    # Enums
    "CandidateStatus",
    "DiscoveryStatus",
    "PriorityLevel",
    "ProviderStatus",
    "ScoreLevel",
    # Exceptions
    "ConfigurationError",
    "DomainValidationError",
    "IdentifierError",
    "KancellShieldError",
    "PriorityValidationError",
    "ResourceError",
    "ScoreValidationError",
    "StateError",
    "URLValidationError",
    "ValidationError",
    # Identifiers
    "BatchId",
    "CandidateId",
    "EventId",
    "ProviderId",
    "RuleId",
    "SourceId",
    "TaskId",
    # Value Objects
    "ConfidenceScore",
    "Domain",
    "Hostname",
    "Priority",
    "Timestamp",
    "URL",
    # Types
    "ConfidenceScoreType",
    "DiscoveryTask",
    "DomainName",
    "EventData",
    "EventEmitter",
    "EventHandler",
    "FilterFunc",
    "is_active_status",
    "is_terminal_status",
    "is_valid_domain",
    "is_valid_priority",
    "is_valid_score",
    "is_valid_url",
    "JSON",
    "Metadata",
    "ProviderName",
    "SearchProvider",
    "ScoreFunc",
    "ValidationFunc",
]
